# Generated by Django 5.2.12 on 2026-07-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_therapistprofile_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='therapist_photos/'),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='therapistprofile',
            name='years_of_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
