# Generated by Django 5.2.12 on 2026-07-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_therapistprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistprofile',
            name='profile_photo',
        ),
    ]
